volumes: 
  traefik-forward-auth-keycloakdb-data:

services:
  traefik:
    image: "traefik:v3.3.5"
    hostname: traefik
    volumes:
      - "./traefik:/traefik"
    command:
      - "--configFile=/traefik/config.yaml"
    ports:
      - "7060:7060"
      - "7070:7070"
    depends_on:
      - oauth2-proxy
      - httpbin

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8080:80

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.2
    hostname: oauth2-proxy
    command: --config /oauth2-proxy/config.toml
    volumes:
      - "./oauth2-proxy:/oauth2-proxy"
    ports:
      - 4180:4180
    depends_on:
      - keycloak  

  keycloakdb:
    image: postgres:16.2-alpine
    hostname: traefik-forward-auth-keycloakdb
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=password
    volumes:
      - traefik-forward-auth-keycloakdb-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    hostname: traefik-forward-auth-keycloak
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://traefik-forward-auth-keycloakdb:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_SCHEMA=public
      # - KC_HOSTNAME=localhost:8082
      - KC_LOG_LEVEL=info
      - KC_FEATURES=docker
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
    ports:
      - "8082:8080"  
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy-headers=forwarded", "--proxy-headers=xforwarded", "--http-port=8080"]
    depends_on:
      - keycloakdb