http_address="0.0.0.0:4180"
skip_provider_button="true"
cookie_secure="false"
pass_access_token="true"
pass_authorization_header="true"

#Traefik
reverse_proxy="true"
upstreams="static://202"

#Keycloak
provider="keycloak-oidc"
oidc_issuer_url="http://localhost:8082/realms/traefik"
client_id = "traefik-service"
client_secret = "8mlmO7UJCsXvGuw8fDgYNRDPnqQwUc3I"
cookie_secret = "F5IF7kNO3oc2MnPsY1k02GpVD6NTMQLWjZ_eyxdTFPg="
email_domains="*"
oidc_extra_audiences=["account"]
code_challenge_method="S256"



