http_address="0.0.0.0:4180"
skip_provider_button="true"
cookie_secure="false"
pass_access_token="true"
pass_authorization_header="true"
set_authorization_header="true"
whitelist_domains=["localhost:*"]

#Traefik
reverse_proxy="true"
upstreams="static://202"

#Keycloak
provider="keycloak-oidc"
oidc_issuer_url="http://localhost:8082/realms/master"
client_id = "oauth2-proxy"
client_secret = "YNdceTpnG3Dvzuk65AG6Pk1YIlcxtcZN"
cookie_secret = "F5IF7kNO3oc2MnPsY1k02GpVD6NTMQLWjZ_eyxdTFPg="
email_domains="*"
oidc_extra_audiences=["account"]



