http:
  middlewares:
    auth-headers:
      headers:
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
    oauth-auth-redirect:
      forwardAuth:
        address: http://localhost:4180
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
    oauth-auth-wo-redirect:
      forwardAuth:
        address: http://localhost:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
    strip-service-prefix:
      stripPrefixRegex:
        regex:
          - "^/[a-zA-Z0-9-+_]+"
  services:
    oauth-backend:
      loadBalancer:
        servers:
          - url: http://localhost:4180
    "8080":
      loadBalancer:
        servers:
          - url: http://localhost:8080
  routers:
    services-oauth2-route:
      rule: "PathPrefix(`/oauth2/`)"
      middlewares:
        - auth-headers
      service: oauth-backend
    8080-no-auto-redirect:
      rule: "PathPrefix(`/no-auto-redirect`)"
      service: "8080"
      middlewares:
        - oauth-auth-wo-redirect     
    "8080":
      rule: "PathPrefix(`/`)"
      service: "8080"
      middlewares:
        - oauth-auth-redirect        
